nome = input("Qual o seu nome?")
print("Olá,", nome+"! Prazer em te conhecer.")
dia = input("Dia = ")
mes = input("Mês = ")
ano = input("Ano = ")
print(nome+", Você nasceu no dia", dia, "de", mes, "de", ano+". Correto?")
