a = input('Digite algo: ')
print('Teste de número:' )
print(a.isnumeric())
print('Teste de letra:')
print(a.isalpha())
print('Teste de alfanumerico:')
print(a.isalnum())
print('Teste de vazio:')
print(a.isprintable())
